FirmaAnket.WebUI/Controllers/PersonalController.cs
using FirmaAnket.Business.Services;
using FirmaAnket.Models;
using FirmaAnket.WebUI.FilterAttributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FirmaAnket.WebUI.Controllers
{
    [_LoginFilterControl]
    public class PersonalController : Controller
    {
        private readonly PersonelService _personelService;
        public PersonalController()
        {
            _personelService = new PersonelService();
        }
        public ActionResult Index()
        {
            if (Session["Admin"] == null)
            {
                return RedirectToAction("SignIn", "Login");
            }
            var model = _personelService.GetList();
            return View(model);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(PersonelDTO model,string Answer)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (Answer==Constants.AnswerType.Yes)
                    {
                        model.isAdmin = true;
                    }
                    else
                    {
                        model.isAdmin = false;
                    }
                    string msg = "";
                    string userName = Session["_loginedUserName"].ToString();
                    _personelService.Save2(model,userName, out msg);
                    return RedirectToAction("Index");

                }
                return View(model);

            }
            catch (Exception)
            {
                return View(model);
            }

        }

        public ActionResult Edit(int id)
        {
            var per = _personelService.GetSingle(id);
            if (per == null)
                return HttpNotFound();
            return View(per);

        }
        [HttpPost]
        public ActionResult Edit(PersonelDTO model,string Answer)
        {
            
            try
            {
                if (ModelState.IsValid)
                {
                    if (Answer == Constants.AnswerType.Yes)
                    {
                        model.isAdmin = true;
                    }
                    else
                    {
                        model.isAdmin = false;
                    }

                    string msg = "";
                    string userName = Session["_loginedUserName"].ToString();
                    _personelService.Update2(model,userName,out msg);
                    return RedirectToAction("Index");
                }
                return View(model);
            }
            catch (Exception)
            {
                return View(model);
            }
        }
        public ActionResult Delete(int id)
        {
            string msg = "";
            var model = _personelService.GetSingle(id);
            if (model == null)
                return HttpNotFound();
            else
                _personelService.Delete(model.ID, out msg);
            return RedirectToAction("Index");
        }


    }
}

FirmaAnket.WebUI/Views/Personal/Create.cshtml
@model FirmaAnket.Models.PersonelDTO
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-body">
        <div class="card-title">Kişi Ekleme Sayfası</div>
        <hr>
        @using (Html.BeginForm("Create", "Personal", FormMethod.Post))
        {
            <form>
                <div class="form-group">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.LabelFor(model => model.NameSurname, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.NameSurname, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NameSurname, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <label for="input-2">Code</label>
                    <input type="text" class="form-control" name="Code" id="input-2" placeholder="Code" maxlength="10" required>
                </div>
                <div class="form-group">
                    <label for="input-3">Şifre</label>
                    <input type="password" class="form-control" name="Password" id="input-3" placeholder="Şifre" maxlength="20" required>
                </div>
                    <label for="input-3">Admin Mi?</label>

                <div class="icheck-metarial-primary icheck-inline">
                    <input type="radio" id="id_1" name="Answer" value="@FirmaAnket.WebUI.Constants.AnswerType.Yes">
                    <label for="id_1">@FirmaAnket.WebUI.Constants.AnswerType.Yes</label>

                    <input type="radio" id="id_2" name="Answer" value="@FirmaAnket.WebUI.Constants.AnswerType.No" checked>
                    <label for="id_2">@FirmaAnket.WebUI.Constants.AnswerType.No</label>
                </div>


                <div class="form-group">
                    <button type="submit" class="btn btn-success shadow-success px-5"><i class="icon-lock"></i> Kaydet</button>
                </div>
            </form>
        }


    </div>
</div>

FirmaAnket.WebUI/Views/Personal/Edit.cshtml
@model FirmaAnket.Models.PersonelDTO
@{

    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-body">
        <div class="card-title">Kişi Düzenleme Sayfası</div>
        <hr>
        @using (Html.BeginForm("Edit", "Personal", FormMethod.Post))
        {
            <form>
                <div class="form-group">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.LabelFor(model => model.NameSurname, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.NameSurname, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NameSurname, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", type = "password" } })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })

                    @*<label for="input-3">Şifre</label>
                        <input type="password" class="form-control" name="Password" id="input-3" placeholder="Şifre" maxlength="20" required>*@
                </div>
                <label for="input-3">Admin Mi?</label>

                <div class="icheck-metarial-primary icheck-inline">
                    @if (Model.isAdmin == true)
                    {
                        <input type="radio" id="id_1" name="Answer" value="@FirmaAnket.WebUI.Constants.AnswerType.Yes" checked>
                        <label for="id_1">@FirmaAnket.WebUI.Constants.AnswerType.Yes</label>

                        <input type="radio" id="id_2" name="Answer" value="@FirmaAnket.WebUI.Constants.AnswerType.No">
                        <label for="id_2">@FirmaAnket.WebUI.Constants.AnswerType.No</label>
                    }
                    else
                    {
                        <input type="radio" id="id_1" name="Answer" value="@FirmaAnket.WebUI.Constants.AnswerType.Yes">
                        <label for="id_1">@FirmaAnket.WebUI.Constants.AnswerType.Yes</label>

                        <input type="radio" id="id_2" name="Answer" value="@FirmaAnket.WebUI.Constants.AnswerType.No" checked>
                        <label for="id_2">@FirmaAnket.WebUI.Constants.AnswerType.No</label>
                    }


                </div>


                <div class="form-group">
                    <button type="submit" class="btn btn-success shadow-success px-5"><i class="icon-lock"></i> Düzenle</button>
                </div>
            </form>
        }


    </div>
</div>

FirmaAnket.WebUI/Views/Personal/Index.cshtml
@model IEnumerable<FirmaAnket.Models.PersonelDTO>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<script src="~/Content/assets/js/jquery.min.js"></script>*@
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<link href="~/Content/assets/plugins/bootstrap-datatable/css/dataTables.bootstrap4.min.css" rel="stylesheet" />



<!--Start Dashboard Content-->
<div class="card">
    <div class="row mt-4">
        <div class="col-12 col-lg-6 col-xl-6">
            <div class="card bg-dark">
                <div class="card-body">
                    <a href="/Personal/Create">
                        <div class="media">
                            <div class="media-body text-left">
                                <h4 class="text-white">Kişi Ekle</h4>
                                <span class="text-white">Kişi eklemek İçin Tıklayın</span>
                            </div>
                            <div class="align-self-center"><span id="dash-chart-1"></span></div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
        <div class="col-12 col-lg-6 col-xl-6">
            <div class="card bg-pinterest">
                <div class="card-body">
                    <div class="media">
                        <div class="media-body text-left">
                            <h4 class="text-white">@Model.Count()</h4>
                            <span class="text-white">Toplam Kişi Sayısı</span>
                        </div>
                        <div class="align-self-center"><span id="dash-chart-2"></span></div>
                    </div>
                </div>
            </div>
        </div>


    </div><!--End Row-->





    <div class="body">
        <div class="table-responsive">
            <table id="example" class="table table-bordered" cellpadding="0" style="width:100%;">
                <thead>
                    <tr class="bg-dark" style="color:white">
                        <td>
                            Ad Soyad
                        </td>
                        <td>
                            Code
                        </td>
                        <td>
                            Şifre
                        </td>
                        <td>
                            Ekleme Tarihi
                        </td>
                        <td>
                            Ekleyen
                        </td><td>
                            Admin Mi?
                        </td>
                        <td>
                            İşlemler
                        </td>


                    </tr>
                </thead>
                <tbody>
                    @foreach (var per in Model)
                    {
                        <tr>
                            <td>@per.NameSurname</td>
                            <td>@per.Code</td>
                            <td>@per.Password</td>
                            <td>@per.CreatedDate</td>
                            <td>@per.CreatedBy</td>
                            <td>@per.isAdmin</td>
                            <td>
                                <a class="btn btn-sm btn-dark text-white" href="/Personal/Edit/@per.ID">
                                    <i class="fa fa fa-pencil">
                                    </i>
                                </a>
                                <a class="btn btn-sm btn-pinterest text-white" onclick="Delete(@per.ID)">
                                    <i class="fa fa fa-trash-o text-white">

                                    </i>
                                </a>
                                <script>
                                    function Delete(id) {
                                        var link = "/Personal/Delete/" + id;
                                        jQuery("#modalLink").attr("href", link);

                                        jQuery("#deletePerson").modal()
                                    }
                                </script>
                            </td>


                        </tr>
                    }

                </tbody>
            </table>

        </div>
    </div>

</div>
<!--End Dashboard Content-->
<script src="~/Content/assets/plugins/bootstrap-datatable/js/jquery.dataTables.min.js"></script>
<script src="~/Content/assets/plugins/bootstrap-datatable/js/dataTables.bootstrap4.min.js"></script>
<script src="~/Content/assets/plugins/bootstrap-datatable/js/dataTables.buttons.min.js"></script>

<script type="text/javascript">
    var jQueryCalis = $.noConflict(true);
    (function ($) {
        $(document).ready(function () {
            $('#example').DataTable({
                "lengthMenu": [[50, 50, -1], [50, 50, "Tümü"]],
                "ordering": true,
                "caseInsensitive": false,
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.12/i18n/Turkish.json"
                }
            });
            var table = $('#example').DataTable();
            $('#example').show();
        });
    })(jQueryCalis);


</script>

<div class="modal fade show" id="deletePerson">
    <div class="modal-dialog">
        <div class="modal-content border-danger">
            <div class="modal-header bg-danger">
                <h5 class="modal-title text-white"><i class="fa fa-star"></i> Modal title</h5>
                <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Kayıt Silenecektir</p><p><b>Emin Misiniz?</b></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-inverse-primary" data-dismiss="modal"><i class="fa fa-times"></i> Vazgeç</button>
                <a class="btn btn-danger" id="modalLink"><i class="fa fa-check-square-o"></i> Sil</a>
            </div>
        </div>
    </div>
</div>