FirmaAnket.WebUI/Controllers/AnswerController.cs
using FirmaAnket.Business.Services;
using FirmaAnket.Models;
using FirmaAnket.WebUI.FilterAttributes;
using FirmaAnket.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FirmaAnket.WebUI.Controllers
{
    [_LoginFilterControl]
    public class AnswerController : Controller
    {
        private readonly PersonelService _personelService;
        private readonly AnswerService _answerService;
        private readonly QuestionService _questionService;
        private readonly AnswerLineService _answerLineService;
        public AnswerController()
        {
            _personelService = new PersonelService();
            _answerService = new AnswerService();
            _questionService = new QuestionService();
            _answerLineService = new AnswerLineService();
        }
        // GET: Answer 
        public ActionResult Index()
        {
            string userCode = Session["_loginedUserCode"].ToString();
            var model = _answerService.GetList().Where(m=>m.UserCode==userCode);
            return View(model);
        }
      
        public ActionResult Create(string Code)
        {
            string userCode = Session["_loginedUserCode"].ToString();
            if (Code == null)
            {
                List<SelectListItem> personList = (from person in _personelService.GetList()
                                                   where person.Code != userCode
                                                   select new SelectListItem
                                                   {
                                                       Text = person.NameSurname,
                                                       Value = person.Code.ToString()
                                                   }).ToList();

                ViewBag.Person = new SelectList(personList.OrderBy(m => m.Text), "Value", "Text");
                var que = _questionService.GetList();
                return View(que);
            }
            else
            {
                CalculateScore(Code);
                return RedirectToAction("Index");
            }

        }

        public void CalculateScore(string code)
        {
            double Yes = 0,No = 0,Result = 0;
            string userCode = Session["_loginedUserCode"].ToString();

            var answer = _answerService.GetList().FirstOrDefault(m => m.PersonalCode == code && m.UserCode == userCode);

            var answerline = _answerLineService.GetList().Where(m => m.AnswerID == answer.ID);

            foreach (var item in answerline)
            {
                if (item.Answer == Constants.AnswerType.Yes)
                {
                    Yes++;
                }
                else
                {
                    No++;
                }
                Result = (Yes / (Yes + No)) * 100;
                if (Result > 79)
                {
                    answer.IsComplete = true;
                }
                else
                {
                    answer.IsComplete = false;
                }
                answer.Score = Result.ToString();

                string msg = "";
                _answerService.Save(answer,out msg);
            }
        }

        //[HttpPost]
        //public ActionResult Create(AnswerLineDTO model)
        //{
        //    try
        //    {
        //        if (ModelState.IsValid)
        //        {
        //            string msg = "";
        //            var ktg = _answerLineService.GetList().Where(p => p.ID == model.ID).FirstOrDefault();

        //            //_answerLineService.Save(model, out msg);
        //            return RedirectToAction("Index");
        //        }
        //        else
        //            return View(model);
        //    }
        //    catch (Exception ex)
        //    {
        //        return View(model);
        //    }
        //}


        public String SendData(AnswerVM model)
        {
            string msg = "";
            //var result = _answerService.Save(model,out msg);

            string userCode = Session["_loginedUserCode"].ToString();
            string userName = Session["_loginedUserName"].ToString();

            var mod = _answerService.GetList().FirstOrDefault(m => m.PersonalCode == model.Code && m.UserCode == userCode);

            if (mod != null)
            {
                AnswerLineDTO b = new AnswerLineDTO();
                b.AnswerID = mod.ID;
                b.Answer = model.Answer;
                b.Question = model.Question;
                SaveAnswerLine(b);
            }
            else
            {
                AnswerDTO answer = new AnswerDTO()
                {
                    PersonalCode = model.Code,
                    PersonalName = model.NameSurname,
                    UserCode = userCode,
                    CreateDate = DateTime.Now,
                    CreatedBy = userName

                };

                _answerService.Save(answer, out msg);
                AnswerLineDTO b = new AnswerLineDTO();
                b.AnswerID = answer.ID;
                b.Answer = model.Answer;
                b.Question = model.Question;
                SaveAnswerLine(b);
            }



            return "True";
        }

        public void SaveAnswerLine(AnswerLineDTO model)
        {
            string msg = "";

            var mod = _answerLineService.GetList().FirstOrDefault(m => m.AnswerID == model.AnswerID && m.Question == model.Question);

            if (mod != null)
            {
                mod.Answer = model.Answer;
            }

            _answerLineService.Save(model, out msg);



        }


        public ActionResult Detail(int? id)
        {
            var model = _answerLineService.GetList().Where(m=>m.AnswerID==id);
            return View(model);
        }

    }
}

FirmaAnket.WebUI/Views/Answer/Create.cshtml
@model IEnumerable<FirmaAnket.Models.QuestionDTO>
@{
    /**/


    Layout = "~/Views/Shared/_Layout.cshtml";
    int number = 1;
    int gomines = 0;
}



<div class="card">
    <div class="card-body">
        <div class="card-title text-center">Anket Cevaplama Sayfası</div>
        <hr>
        @using (Html.BeginForm("Create", "Answer"))
        {
        <form>
            <div class="form-group">
                @Html.DropDownList("Code", (SelectList)ViewBag.Person, "Lütfen Kişi Seçiniz", new { @class = "form-control" })
            </div>

            @foreach (var item in Model)
            {
                <input name="@item.Question" id="Question_@item.ID" value="@item.Question" type="hidden" />

                <span style="font-weight:bold">@number)</span>
                @item.Question
                <br /><br />


                <div class="icheck-metarial-primary icheck-inline">
                    <input type="radio" id="id_@item.ID" name="Answer_@item.ID" class="radio_@item.ID" value="@FirmaAnket.WebUI.Constants.AnswerType.Yes">
                    <label for="id_@item.ID">@FirmaAnket.WebUI.Constants.AnswerType.Yes</label>

                    <input type="radio" id="id_@gomines" name="Answer_@item.ID" class="radio_@item.ID" value="@FirmaAnket.WebUI.Constants.AnswerType.No">
                    <label for="id_@gomines">@FirmaAnket.WebUI.Constants.AnswerType.No</label>
                </div>


              

                <script>
                        $(document).ready(function () {
                            $('.radio_@item.ID').click(function () {

                        var formdata = new FormData();
                        var code = $('#Code').val();
                                formdata.set("Code", code);

                        var namesurname = $('#Code :selected').text();
                                formdata.set("NameSurname", namesurname);

                        var quesition = $('#Question_@item.ID').val();
                        formdata.set("Question", quesition);
                        var answer = $('input[name="Answer_@item.ID"]:checked').val();
                        formdata.set("Answer", answer);
                        if (code == '') {
                            $('#warningMessage').modal('show');
                            return;
                        }
                                $.ajax({
                                    url: "/Answer/SendData",
                                    data: formdata,
                                    type: "POST",
                                    cache: false,
                                    contentType: false,
                                    processData: false,
                                    successs: function (data) {
                                        if (data == "True") {
                                        }
                                    },
                                    error: function (data) {
                                        alert("Ekleme işlemi sırasında bir hata meydana geldi!");
                                    }
                                });
                            });
                        });
                </script>

                gomines--;
                number++;
            }




            <div class="form-group">
                <button type="submit" class="btn btn-success shadow-success px-5"><i class="icon-lock"></i> Kaydet</button>
            </div>
        </form>
        }


    </div>
</div>

<div class="modal fade show" id="warningMessage">
    <div class="modal-dialog">
        <div class="modal-content border-warning">
            <div class="modal-header bg-warning">
                <h5 class="modal-title text-white"><i class="fa fa-star"></i>Uyarı</h5>
                <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Lütfen Kişi</p><p><b>Seçiniz</b></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-inverse-primary" data-dismiss="modal"><i class="fa fa-times"></i> Kapat</button>
               
            </div>
        </div>
    </div>
</div>

FirmaAnket.WebUI/Views/Answer/Detail.cshtml
@model IEnumerable<FirmaAnket.Models.AnswerLineDTO>
@{

    Layout = "~/Views/Shared/_Layout.cshtml";
    int number = 1;
}

<div class="card">






    <div class="card-body">
        <h4 class="text-center">Anket Detay Sayfası</h4>
        <div class="table-responsive">

            @foreach (var item in Model)
            {
                <span><b>@number)</b>@item.Question</span>
                <br /><span><b>@item.Answer</b></span>
                <br /><br /><br />
                number++;
            }

        </div>
    </div>
</div>

FirmaAnket.WebUI/Views/Answer/Index.cshtml
@model IEnumerable<FirmaAnket.Models.AnswerDTO>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<script src="~/Content/assets/js/jquery.min.js"></script>*@
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<link href="~/Content/assets/plugins/bootstrap-datatable/css/dataTables.bootstrap4.min.css" rel="stylesheet" />



<!--Start Dashboard Content-->
<div class="card">
    <div class="row mt-4">
        <div class="col-12 col-lg-6 col-xl-6">
            <div class="card bg-dark">
                <div class="card-body">
                    <a href="/Answer/Create">
                        <div class="media">
                            <div class="media-body text-left">
                                <h4 class="text-white">Anket Ekle</h4>
                                <span class="text-white">Anket eklemek İçin Tıklayın</span>
                            </div>
                            <div class="align-self-center"><span id="dash-chart-1"></span></div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
        <div class="col-12 col-lg-6 col-xl-6">
            <div class="card bg-pinterest">
                <div class="card-body">
                    <div class="media">
                        <div class="media-body text-left">
                            <h4 class="text-white">@Model.Count()</h4>
                            <span class="text-white">Toplam Anket Sayısı</span>
                        </div>
                        <div class="align-self-center"><span id="dash-chart-2"></span></div>
                    </div>
                </div>
            </div>
        </div>


    </div><!--End Row-->





    <div class="body">
        <div class="table-responsive">
            <table id="example" class="table table-bordered" cellpadding="0" style="width:100%;">
                <thead>
                    <tr class="bg-dark" style="color:white">
                        <td>
                            Ad Soyad
                        </td>
                        <td>
                            Code
                        </td>
                        <td>
                            Score
                        </td>
                        <td>
                            Tamamlanma durumu
                        </td>
                        <td>
                            Ekleme Tarihi
                        </td>
                        <td>
                            Ekleyen
                        </td>
                        <td>
                            İşlemler
                        </td>


                    </tr>
                </thead>
                <tbody>
                    @foreach (var per in Model)
                    {
                        <tr>
                            <td>@per.PersonalName</td>
                            <td>@per.PersonalCode</td>
                            <td>@per.Score</td>
                            @if (per.IsComplete == true)
                            {
                                <td>@FirmaAnket.WebUI.Constants.AnswerType.Yes</td>
                            }
                            else
                            {
                                <td>@FirmaAnket.WebUI.Constants.AnswerType.No</td>
                            }

                            <td>@per.CreateDate</td>
                            <td>@per.CreatedBy</td>
                            <td>
                                <a class="btn btn-sm btn-dark text-white" href="/Answer/Detail/@per.ID">
                                    <i class="fa fa fa-pencil">
                                    </i>
                                </a>


                            </td>


                        </tr>
                    }

                </tbody>
            </table>

        </div>
    </div>

</div>
<!--End Dashboard Content-->
<script src="~/Content/assets/plugins/bootstrap-datatable/js/jquery.dataTables.min.js"></script>
<script src="~/Content/assets/plugins/bootstrap-datatable/js/dataTables.bootstrap4.min.js"></script>
<script src="~/Content/assets/plugins/bootstrap-datatable/js/dataTables.buttons.min.js"></script>

<script type="text/javascript">
    var jQueryCalis = $.noConflict(true);
    (function ($) {
        $(document).ready(function () {
            $('#example').DataTable({
                "lengthMenu": [[50, 50, -1], [50, 50, "Tümü"]],
                "ordering": true,
                "caseInsensitive": false,
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.12/i18n/Turkish.json"
                }
            });
            var table = $('#example').DataTable();
            $('#example').show();
        });
    })(jQueryCalis);


</script>