FirmaAnket.WebUI/Controllers/QuestionController.cs
using FirmaAnket.Business.Services;
using FirmaAnket.Models;
using FirmaAnket.WebUI.FilterAttributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FirmaAnket.WebUI.Controllers
{
    [_LoginFilterControl]
    public class QuestionController : Controller
    {
        private readonly QuestionService _questionService;
        public QuestionController()
        {
            _questionService = new QuestionService();
        }
        // GET: Question
        public ActionResult Index()
        {
            if (Session["Admin"]==null)
            {
                return RedirectToAction("SignIn", "Login");
            }
            else
            {
                var model = _questionService.GetList();
                return View(model);
            }
           
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(QuestionDTO model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string msg = "";
                    _questionService.Save(model, out msg);
                    return RedirectToAction("Index");
                }
                return View(model);
            }
            catch (Exception)
            {
                return View(model);
            }
        }
        public ActionResult Edit(int id)
        {
            var model = _questionService.GetSingle(id);
            if (model == null)
                return HttpNotFound();
            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(QuestionDTO model)
        {
            try
            {
                string msg = "";
                _questionService.Update(model,out msg);
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return View(model);
            }

        }

        public ActionResult Delete(int id)
        {
            string msg = "";
            var model = _questionService.GetSingle(id);
            if (model == null)
                return HttpNotFound();
            else
                _questionService.Delete(model.ID,out msg);
            return RedirectToAction("Index");
        }
    }
}

FirmaAnket.WebUI/Views/Question/Create.cshtml
@model FirmaAnket.Models.QuestionDTO
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="card">
    <div class="card-body">
        <div class="card-title">Soru Ekleme Sayfası</div>
        <hr>
        @using (Html.BeginForm("Create", "Question", FormMethod.Post))
        {
            <form>
                <div class="form-group">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.LabelFor(model => model.Question, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.Question, new { htmlAttributes = new { @class = "form-control" ,type="area",maxlenght="250"} })
                    @Html.ValidationMessageFor(model => model.Question, "", new { @class = "text-danger" })
                </div>
              
                <div class="form-group">
                    <button type="submit" class="btn btn-success shadow-success px-5"><i class="icon-lock"></i> Kaydet</button>
                </div>
            </form>
        }


    </div>
</div>

FirmaAnket.WebUI/Views/Question/Edit.cshtml
@model FirmaAnket.Models.QuestionDTO
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-body">
        <div class="card-title">Soru Ekleme Sayfası</div>
        <hr>
        @using (Html.BeginForm("Edit", "Question", FormMethod.Post))
        {
        <form>
            @*<div class="form-group">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.LabelFor(model => model.Question, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.Question, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Question, "", new { @class = "text-danger" })
            </div>*@
            <div class="form-group">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.LabelFor(model => model.Question, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.Question, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Question, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-success shadow-success px-5"><i class="icon-lock"></i> Düzenle</button>
            </div>
        </form>
        }


    </div>
</div>

FirmaAnket.WebUI/Views/Question/Index.cshtml
@model IEnumerable<FirmaAnket.Models.QuestionDTO>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<script src="~/Content/assets/js/jquery.min.js"></script>*@
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<link href="~/Content/assets/plugins/bootstrap-datatable/css/dataTables.bootstrap4.min.css" rel="stylesheet" />



<!--Start Dashboard Content-->
<div class="card">
    <div class="row mt-4">
        <div class="col-12 col-lg-6 col-xl-6">
            <div class="card bg-dark">
                <div class="card-body">
                    <a href="/Question/Create">
                        <div class="media">
                            <div class="media-body text-left">
                                <h4 class="text-white">Soru Ekle</h4>
                                <span class="text-white">Soru eklemek İçin Tıklayın</span>
                            </div>
                            <div class="align-self-center"><span id="dash-chart-1"></span></div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
        <div class="col-12 col-lg-6 col-xl-6">
            <div class="card bg-pinterest">
                <div class="card-body">
                    <div class="media">
                        <div class="media-body text-left">
                            <h4 class="text-white">@Model.Count()</h4>
                            <span class="text-white">Toplam Soru Sayısı</span>
                        </div>
                        <div class="align-self-center"><span id="dash-chart-2"></span></div>
                    </div>
                </div>
            </div>
        </div>


    </div><!--End Row-->





    <div class="body">
        <div class="table-responsive">
            <table id="example" class="table table-bordered" cellpadding="0" style="width:100%;">
                <thead>
                    <tr class="bg-dark" style="color:white">
                        <td>
                            Soru
                        </td>
                        
                        <td>
                            Ekleme Tarihi
                        </td>
                        <td>
                            Ekleyen
                        </td>
                        <td>
                            İşlemler
                        </td>


                    </tr>
                </thead>
                <tbody>
                    @foreach (var per in Model)
                    {
                        <tr>
                            <td>@per.Question</td>
                            
                            <td>@per.CreatedDate</td>
                            <td>@per.CreatedBy</td>
                            <td>
                                <a class="btn btn-sm btn-dark text-white" href="/Question/Edit/@per.ID">
                                    <i class="fa fa fa-pencil">
                                    </i>
                                </a>
                                <a class="btn btn-sm btn-pinterest text-white" onclick="Delete(@per.ID)">
                                    <i class="fa fa fa-trash-o text-white">

                                    </i>
                                </a>
                                <script>
                                    function Delete(id) {
                                        var link = "/Question/Delete/" + id;
                                        jQuery("#modalLink").attr("href", link);

                                        jQuery("#deletePerson").modal()
                                    }
                                </script>
                            </td>


                        </tr>
                    }

                </tbody>
            </table>

        </div>
    </div>

</div>
<!--End Dashboard Content-->
<script src="~/Content/assets/plugins/bootstrap-datatable/js/jquery.dataTables.min.js"></script>
<script src="~/Content/assets/plugins/bootstrap-datatable/js/dataTables.bootstrap4.min.js"></script>
<script src="~/Content/assets/plugins/bootstrap-datatable/js/dataTables.buttons.min.js"></script>

<script type="text/javascript">
    var jQueryCalis = $.noConflict(true);
    (function ($) {
        $(document).ready(function () {
            $('#example').DataTable({
                "lengthMenu": [[50, 50, -1], [50, 50, "Tümü"]],
                "ordering": true,
                "caseInsensitive": false,
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.12/i18n/Turkish.json"
                }
            });
            var table = $('#example').DataTable();
            $('#example').show();
        });
    })(jQueryCalis);


</script>

<div class="modal fade show" id="deletePerson">
    <div class="modal-dialog">
        <div class="modal-content border-danger">
            <div class="modal-header bg-danger">
                <h5 class="modal-title text-white"><i class="fa fa-star"></i> Modal title</h5>
                <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Kayıt Silenecektir</p><p><b>Emin Misiniz?</b></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-inverse-primary" data-dismiss="modal"><i class="fa fa-times"></i> Vazgeç</button>
                <a class="btn btn-danger" id="modalLink"><i class="fa fa-check-square-o"></i> Sil</a>
            </div>
        </div>
    </div>
</div>